  name: 'Create File'
  description: 'Github Action to create a file from environment variables or Github Secrets'
  author: 'Daniel Harms'
  inputs:
    file_name:
      description: 'The filename to be created'
    file_contents:
      description: 'Contents to write to file'
  runs:
    using: 'docker'
    image: 'Dockerfile'
